### ISSUE TITLE
Support for non-numpy docstring types?

### ISSUE THREAD

**Issue by SamuelMarks** [Chilipp/funcargparse#1]
I like the idea of this repository. Did a quick web search to find it, if I hadn't found it, I would write my own version!

Anyway, I'm building on a bunch of codebases, which are mostly ReST style.

Instead of using [docrep](https://docrep.readthedocs.io), have you considered using [docstring-parser](https://pypi.org/project/docstring-parser)? - It supports ReST, Google, and Numpydoc.

Interested in your thoughts @Chilipp; depending on your perspective, happy to work on the PR.

**Comment by Chilipp** [comment]
Hi @SamuelMarks, yes, this would be great, thanks for the hint and for pointing me towards docstring-parser. I might actually base `docrep` on this package, I think they integrate pretty well.

> depending on your perspective, happy to work on the PR.

Yes, please. thanks a lot!

**Comment by SamuelMarks** [comment]
Great I'll see what I can do.

Also sent through a PR here https://github.com/rubik/mando/pull/50

Your project seem reasonably similar. Any chance for a license change so that code can be shared between the two?

**Comment by Chilipp** [comment]
> Any chance for a license change so that code can be shared between the two?

sure, we can change the license into MIT @SamuelMarks, that's fine. Actually it might be worth thinking about deprecating the `funcargparse` package then in favor of `mando`. What do you think?

**Comment by SamuelMarks** [comment]
Either works. `mando` is interesting, but until my tests succeed I'm open to alternatives.

**Comment by SamuelMarks** [comment]
FYI: I wrote my own solution https://github.com/SamuelMarks/doctrans
